// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDU.Models;

namespace NDU.Migrations
{
    [DbContext(typeof(NDUContext))]
    [Migration("20190301180134_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NDU.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ConsiderationDate");

                    b.Property<string>("DocState");

                    b.Property<string>("EDPNOU");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<DateTime>("FilingDate");

                    b.Property<string>("Name");

                    b.Property<string>("RecipientId");

                    b.Property<DateTime>("RecipientRegDate");

                    b.Property<string>("SenderId");

                    b.Property<DateTime>("SenderRegDate");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
